[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.cursor]
text = "#272822"
cursor = "#f8f8f2"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"


[font]
size = 18

[font.normal]
family = "Fantasque Sans Mono"
style = "Bold"

# [[keyboard.bindings]]
# action = "SpawnNewInstance"
# key = "N"
# mods = "COntrol"

# [schemes.Apus.bright]
# black = "#2D3742"
# blue = "#FC9867"
# cyan = "#78DCE8"
# green = "#A9DC76"
# magenta = "#AB9DF2"
# red = "#FF6188"
# white = "#FCFCFA"
# yellow = "#FFD866"
# 
# [schemes.Apus.normal]
# black = "#2D3742"
# blue = "#FC9867"
# cyan = "#78DCE8"
# green = "#A9DC76"
# magenta = "#AB9DF2"
# red = "#FF6188"
# white = "#FCFCFA"
# yellow = "#FFD866"
# 
# [schemes.Apus.primary]
# background = "#2D3742"
# foreground = "#ACE3FF"
# 
# [schemes.Default.bright]
# black = "#666666"
# blue = "#7aa6da"
# cyan = "#70c0b1"
# green = "#b9ca4a"
# magenta = "#c397d8"
# red = "#d54e53"
# white = "#eaeaea"
# yellow = "#e7c547"
# 
# [schemes.Default.dim]
# black = "#131415"
# blue = "#556a7d"
# cyan = "#5b7d78"
# green = "#777c44"
# magenta = "#75617b"
# red = "#864343"
# white = "#828482"
# yellow = "#9e824c"
# 
# [schemes.Default.normal]
# black = "#1d1f21"
# blue = "#81a2be"
# cyan = "#8abeb7"
# green = "#b5bd68"
# magenta = "#b294bb"
# red = "#cc6666"
# white = "#c5c8c6"
# yellow = "#f0c674"
# 
# [schemes.Default.primary]
# background = "#1d1f21"
# foreground = "#c5c8c6"
# 
# [schemes.Monokai.bright]
# black = "#727072"
# blue = "#FC9867"
# cyan = "#78DCE8"
# green = "#A9DC76"
# magenta = "#AB9DF2"
# red = "#FF6188"
# white = "#FCFCFA"
# yellow = "#FFD866"
# 
# [schemes.Monokai.normal]
# black = "#403E41"
# blue = "#FC9867"
# cyan = "#78DCE8"
# green = "#A9DC76"
# magenta = "#AB9DF2"
# red = "#FF6188"
# white = "#FCFCFA"
# yellow = "#FFD866"
# 
# [schemes.Monokai.primary]
# background = "#2D2A2E"
# foreground = "#FCFCFA"
# 
# [schemes.Nordic.bright]
# black = "#353C4A"
# blue = "#81A1C1"
# cyan = "#88C0D0"
# green = "#A3BE8C"
# magenta = "#B48EAD"
# red = "#BF616A"
# white = "#E5E9F0"
# yellow = "#EBCB8B"
# 
# [schemes.Nordic.normal]
# black = "#2E3440"
# blue = "#81A1C1"
# cyan = "#88C0D0"
# green = "#A3BE8C"
# magenta = "#B48EAD"
# red = "#BF616A"
# white = "#E5E9F0"
# yellow = "#EBCB8B"
# 
# [schemes.Nordic.primary]
# background = "#2E3440"
# foreground = "#ACE3FF"
# 
# [schemes.Tomorrow.bright]
# black = "#666666"
# blue = "#81a2be"
# cyan = "#54ced6"
# green = "#9ec400"
# magenta = "#b77ee0"
# red = "#ff3334"
# white = "#282a2e"
# yellow = "#f0c674"
# 
# [schemes.Tomorrow.cursor]
# cursor = "#ffffff"
# text = "#1d1f21"
# 
# [schemes.Tomorrow.normal]
# black = "#1d1f21"
# blue = "#81a2be"
# cyan = "#70c0ba"
# green = "#b5bd68"
# magenta = "#b294bb"
# red = "#cc6666"
# white = "#ffffff"
# yellow = "#e6c547"
# 
# [schemes.Xterm.bright]
# black = "#7f7f7f"
# blue = "#5c5cff"
# cyan = "#00ffff"
# green = "#00ff00"
# magenta = "#ff00ff"
# red = "#ff0000"
# white = "#ffffff"
# yellow = "#ffff00"
# 
# [schemes.Xterm.normal]
# black = "#000000"
# blue = "#0000ee"
# cyan = "#00cdcd"
# green = "#00cd00"
# magenta = "#cd00cd"
# red = "#cd0000"
# white = "#e5e5e5"
# yellow = "#cdcd00"
# 
# [schemes.Xterm.primary]
# background = "#000000"
# foreground = "#ffffff"

[shell]
program = "/bin/fish"

[window]
opacity = 0.5

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 18
y = 13
