#!/bin/bash

RES="1920x1080"
if xrandr | grep "3440x1440" | grep "connected"; then
	#set monitor resolution (affects wallpaper dir)
	RES="3440x1440"		
fi

DIR=$HOME/Pictures/wallpapers/$RES
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

swww query || swww init

#change-wallpaper using swww
swww img ${DIR}/${RANDOMPICS} --transition-fps 30 --transition-type any --transition-duration 3

